from ROOT import TFile, TH1D, TCanvas, TLegend, gStyle, TGaxis, gPad

gStyle.SetOptStat(0)
#f = TFile('histos.root','read')
f = TFile('histos_Fprompt-0.62.root','read')

nuc = f.Get('survProbNuc')
gam = f.Get('survProbGam')
fnuc = f.Get('fnuc')
fgam = f.Get('fgam')
tnuc = f.Get('decspnuc')
tgam = f.Get('decspgam')

c1 = TCanvas('c1','',800,640)
c2 = TCanvas('c2','',800,640)
c3 = TCanvas('c3','',800,640)
c4 = TCanvas('c4','',800,640)

c1.cd()
nuc.SetYTitle('fraction of n induced #gamma')
nuc.SetXTitle('number of PE')
nuc.Rebin(3)
nuc.Scale(0.33)
nuc.Draw()
c1.Update()

c2.cd()
gam.SetLineColor(2)
gam.SetYTitle('fraction of misidentified #gamma')
gam.SetXTitle('number of PE')
gam.Rebin(3)
gam.Scale(0.33)
gam.Draw()
c2.Update()

c3.cd()
fnuc.SetStats(0)
fnuc.SetXTitle('F_{prompt}')
fnuc.SetYTitle('Entries')
fnuc.Rebin(4)
fnuc.Scale(0.25)
fnuc.Draw()
fgam.Rebin(4)
fgam.Scale(0.25)
fgam.Draw('same')

leg = TLegend(0.6,0.75,0.95,0.95)
leg.AddEntry(fnuc,'nR','l')
leg.AddEntry(fgam,'eR','l')
leg.SetFillColor(0)
leg.SetBorderSize(0)
leg.Draw()
c3.Update()

c4.cd()
c4.SetLogy()
c4.SetLogx()
tnuc.SetStats(0)
tnuc.SetYTitle('Entries')
tnuc.SetXTitle('time (ns)')
intNuc = tnuc.Integral(0,200)
intGam = tgam.Integral(0,200)
sf = intNuc/intGam
print 'sf', sf,'\n'
tgam.Scale(sf)
tnuc.Draw()
tgam.Draw('same')
leg.Draw()
c4.Update()

raw_input() 
